feign:
  hystrix:
    enabled: true

hystrix:
  command:
    FeignProductService#getProducts():
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
        circuitBreaker:
          requestVolumeThreshold: 1 # 감시 시간 내 요청 수, 기본값 20
          errorThresholdPercentage: 50 # 요청 대비 오류율, 기본값 50
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 1 # 감시 시간 내 요청 수, 기본값 20
        errorThresholdPercentage: 50 # 요청 대비 오류율, 기본값 50

product:
  ribbon:
    ConnectTimeout: 3000

eureka:
  instance:
    prefer-ip-address: true
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: display
  kafka:
    consumer:
      group-id: myGroup
    bootstrap-servers: localhost:9092

kafka:
  topics:
    test: order