#feign:
#  client:
#    config:
#      demoClient:
#        connectTimeout: 10000
#        readTimeout: 1000
#      default:
#        connectTimeout: 10000
#        readTimeout: 1000

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 1000
